version: "2"

services:
  hass:
      container_name: hass
      image: homeassistant/home-assistant:stable
      volumes: 
        - ./hass:/config
      environment:
        - TZ=America/New_York
      restart: always
      network_mode: host

